package com.crzsc.plugin.utils

import com.crzsc.plugin.setting.PluginSetting
import com.crzsc.plugin.utils.PluginUtils.showNotify
import com.crzsc.plugin.utils.PluginUtils.toLowCamelCase
import com.crzsc.plugin.utils.PluginUtils.toUpperCaseFirst
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.PsiDocumentManager
import com.intellij.psi.PsiManager

class FileGenerator(private val project: Project) {
    private val ignoreDir = listOf("2.0x", "3.0x", "Mx", "Nx")
    fun generate() {
        WriteCommandAction.runWriteCommandAction(project) {
            val map = mutableMapOf<String, String>()
            val file = FileHelper.getAssetsFolder(project)
            if (file == null) {
                showNotify("Please configure your assets path in pubspec.yaml")
                return@runWriteCommandAction
            }
            generateFileMap(file, map)
            if (map.isEmpty()) {
                showNotify("assets path is empty")
                return@runWriteCommandAction
            }
            val content = StringBuilder()
            content.append("///This file is automatically generated. DO NOT EDIT, all your changes would be lost.\n")
            var className = PluginSetting.getInstance().className
            if (className.isNullOrEmpty()) {
                className = "Assets"
            }
            content.append("class $className {\n  $className._();\n\n")
            map.toSortedMap().forEach {
                content.append("  static const String ${it.key} = '${it.value}';\n")
            }
            content.append("\n}\n")
            val psiManager = PsiManager.getInstance(project)
            val psiDocumentManager = PsiDocumentManager.getInstance(project)
            FileHelper.getGeneratedFile(project).let { file ->
                psiManager.findFile(file)?.let { dartFile ->
                    psiDocumentManager.getDocument(dartFile)?.let { document ->
                        if (document.text != content.toString()) {
                            document.setText(content)
                            psiDocumentManager.commitDocument(document)
                            PluginUtils.showNotify("assets generate succeed")
                        } else {
                            PluginUtils.showNotify("nothing changed")
                        }
                    }
                }
            }
        }
    }

    private fun generateFileMap(root: VirtualFile, map: MutableMap<String, String>) {
        root.children.filter {
            !it.name.startsWith('.') && checkName(it.name)
        }.forEach {
            if (it.isDirectory) {
                generateFileMap(it, map)
            } else {
                var key = it.nameWithoutExtension.toLowCamelCase()///fileName style
                val value = it.path.removePrefix("${project.basePath}/")
                if (PluginSetting.getInstance().namedWithParent) {
                    it.parent?.let { parent ->
                        key = "${parent.name.toLowCamelCase()}${key.toUpperCaseFirst()}"
                        if (map.containsKey(key)) {
                            key = "${parent.parent.name.toLowCamelCase()}${key.toUpperCaseFirst()}"
                        }
                        map[key] = value
                    }
                } else {
                    map[key] = value
                }
            }
        }
    }

    private fun checkName(name: String): Boolean {
        return !ignoreDir.contains(name)
    }

}